apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-kafka
  namespace: default
  labels:
    k8s-app: fluentd-kafka
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-kafka
  labels:
    k8s-app: fluentd-kafka
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-kafka
  labels:
    k8s-app: fluentd-kafka
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: fluentd-kafka
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-kafka
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-kafka-v0.0.1
  namespace: default
  labels:
    k8s-app: fluentd-kafka
    version: v0.0.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-kafka
      version: v0.0.1
  template:
    metadata:
      labels:
        k8s-app: fluentd-kafka
        kubernetes.io/cluster-service: "true"
        version: v0.0.1
    spec:
      serviceAccountName: fluentd-kafka
      containers:
        - name: fluentd-kafka
          image: megaease/fluentd-kubernetes:v1.14.0-debian-kafka2-easelog-v1.0.1
          env:
            - name: FLUENT_KAFKA2_BROKERS
              value: kafka-1:9092,kafka-2:9092,kafka-3:9092
            - name: FLUENT_KAFKA2_DEFAULT_TOPIC
              value: logs
            - name: FLUENT_KAFKA2_COMPRESSION_CODEC
              value: nil
            - name: FLUENT_KAFKA2_MAX_SEND_LIMIT_BYTES
              value: "1000000"
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /data/docker/docker/containers
              readOnly: true
            - name: config-volume
              mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /data/docker/docker/containers
        - name: config-volume
          configMap:
            name: fluentd-kafka-config-v0.0.1

